default: &default
  host: localhost
  user: root
  password: password
  adapter: mysql

development:
  <<: *default
  db: crystal_database_development

test:
  <<: *default
  db: crystal_database_test

production:
  <<: *default
  db: crystal_database_production